### ISSUE TITLE
AttributeDateTime::GetDateFormat() not found

### ISSUE THREAD

**Issue by IncubusRK** [itop-itsm-ru/workorder-mgmt#1]
In itop-cron.log got errors:
AttributeDateTime::GetDateFormat() not found
in main.workorder-mgmt.php on Line 16
Using iTop 2.3.1-2832

**Comment by vbkunin** [comment]
Hi! Currently, this module works with iTop up to version 2.2. And it isn't recommended for production use because it's still in a beta state.

You can try to replace AttributeDateTime::GetDateFormat() with AttributeDateTime::GetFormat() and reinstall the module. It should works.

The new version of the module that will be compatible with iTop 2.3.1 and higher is under development.

**Comment by IncubusRK** [comment]
Thank you!
